name: projectname
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - ipykernel
  - jupyterlab
  # below packages need to be installed with pip (aren't available in conda-forge)
  # - pip
  # - pip:
  #     -
